### ISSUE TITLE
Unable to connect to remote server & The remote name could not be resolved

### ISSUE THREAD

**Issue by VedPatel2254** [SpotX-Official/SpotX#471]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: giving me error while installation 
- Windows: 11
- PowerShell: 10.0.22621
```

### 📝 Description

when i click on Install_New_theme i get error like i given below 
also i get error while installing Spicetify

this error is coming up

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/88715506/8a4ceb00-b734-4ece-ac68-881718c94ad5)

**Comment by amd64fox** [comment]
you didn't read the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-get-the-error-%22Unable-to-connect-to-remote-server%22-or-%22The-remote-name-could-not-be-resolved%22-while-running-the-install)

**Comment by amd64fox** [comment]
need some feedback from users who are experiencing this issue:

need to follow 3 simple steps:

- Click on [link #1](https://raw.githubusercontent.com/amd64fox/Test/main/test.txt).
- Click on [link #2](https://cdn.statically.io/gh/amd64fox/Test/main/test.txt).
- Leave a comment here describing the response you received after visiting the links.

**Comment by VedPatel2254** [comment]
it get solved i don't know how i install it again and it get solved

**Comment by Angry21** [comment]
> need some feedback from users who are experiencing this issue:
> 
> need to follow 3 simple steps:
> 
> * Click on [link #1](https://raw.githubusercontent.com/amd64fox/Test/main/test.txt).
> * Click on [link #2](https://cdn.statically.io/gh/amd64fox/Test/main/test.txt).
> * Leave a comment here describing the response you received after visiting the links.

the links are not opening

**Comment by amd64fox** [comment]
@Angry21 
have you tried the 1st and 2nd links?
what specific error are they displaying?
have you tried clicking the links again?

**Comment by Xe-ro7** [comment]
<details>
<summary><small>Screenshots</small></summary><p>
  
![Screenshot_2023-08-20-00-14-25-780_com android chrome-edit](https://github.com/amd64fox/SpotX/assets/66234646/1ffd6e39-6e72-4818-bb2f-be54e629069b)
![Screenshot_2023-08-20-00-14-45-241_com android chrome-edit](https://github.com/amd64fox/SpotX/assets/66234646/bb87e72f-6ee9-4753-accb-66b22774b679)

</details>

**Comment by Xe-ro7** [comment]
First pic if of 1st link
And second pic is of 2nd link

**Comment by amd64fox** [comment]
@Xe-ro7 
thanks for the feedback, are you from India?

**Comment by Angry21** [comment]
Yes

**Comment by Xe-ro7** [comment]
> @Xe-ro7 
> thanks for the feedback, are you from India?

Yes

**Comment by Synthylich** [comment]
same prob

**Comment by amd64fox** [comment]
@Synthylich 
[read](https://github.com/amd64fox/SpotX/issues/471#issuecomment-1676438087)

**Comment by Angry21** [comment]
> @Synthylich [read](https://github.com/amd64fox/SpotX/issues/471#issuecomment-1676438087)

same prom bro it is not loading just a blank screen

**Comment by amd64fox** [comment]
@Angry21 
Your approximate response should look like [this](https://github.com/amd64fox/SpotX/issues/471#issuecomment-1685082649)

**Comment by Angry21** [comment]
> @Angry21 Your approximate response should look like [this](https://github.com/amd64fox/SpotX/issues/471#issuecomment-1685082649)

yaa
it is looking like that

**Comment by amd64fox** [comment]
send your results as screenshots, thanks

**Comment by Angry21** [comment]
sure

<details>
<summary><small>Screenshots</small></summary><p>


![image_2023-08-23_111701301](https://github.com/amd64fox/SpotX/assets/136931517/09f54b62-0950-48ad-9fa6-3ab0b0df39e3)
![image](https://github.com/amd64fox/SpotX/assets/136931517/174d061e-68c8-4975-878c-16d713d0e978)

</details>

**Comment by amd64fox** [comment]
In your case, both links are working

**Comment by Angry21** [comment]
> In your case, both links are working

but nothing is poping up they are just blank

**Comment by Synthylich** [comment]
> @Synthylich [read](https://github.com/amd64fox/SpotX/issues/471#issuecomment-1676438087)

now its works
but i seen result same as user Xe-ro7 https://github.com/amd64fox/SpotX/issues/471#issuecomment-1685082649

**Comment by Synthylich** [comment]
me helped vpn
seems ISP issue
@amd64fox just like user @Xe-ro7 https://github.com/amd64fox/SpotX/issues/471#issuecomment-1685082649

**Comment by amd64fox** [comment]
thanks everyone for the help, changed the host for all raw links to [cdn.statically.io](cdn.statically.io)

**Comment by sharunkumar** [comment]
> seems ISP issue

kinda curious, which provider is blocking raw.githubusercontent.com? 😅

**Comment by amd64fox** [comment]
I have no idea which specific providers are doing this; we only know the countries that frequently abuse this, which are India and occasionally Egypt

**Comment by amd64fox** [comment]
Unfortunately rolled back to raw.githubusercontent.com as cdn.statically.io refused to work on win 7-8.1

as there will be more time, I will probably fix it through the github pages

**Comment by sharunkumar** [comment]
maybe have cdn.statically.io as a fallback when raw.githubusercontent.com fails?

also I think the fact that ISP is blocking the website does not mean that we should re-host (like what happens when they block statically?). since someone pointed out above that it worked with VPN, should be a temporary workaround for now

**Comment by amd64fox** [comment]
> since someone pointed out above that it worked with VPN, should be a temporary workaround for now

Yes, this is a temporary solution that has been in our [FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-get-the-error-%22Unable-to-connect-to-remote-server%22-or-%22The-remote-name-could-not-be-resolved%22-while-running-the-install) for a long time.


> maybe have cdn.statically.io as a fallback when raw.githubusercontent.com fails?

It's the first thing that came to my mind, but it would complicate the code in the patcher and in all batch files. It seems easier to me to create a mirror using GitHub "Pages" or something similar.


> like what happens when they block statically?

If making requests from Windows 7-8.1 to cdn.statically.io via iwr, you'll encounter a certificate error, and it's not fixed by the standard command 
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
even though this has always worked for most other hosts. However, if you make the exact same request using curl with certificate verification disabled, the request will be successful. Therefore, it appears to be some issue with iwr.

**Comment by Synthylich** [comment]
Серёга, всё равно не работает, даже с этим cdn.statically.io, у меня просто вставало всё на надписи "Добро пожаловать в Windows", и всё

**Comment by Synthylich** [comment]
still does not work, even with this cdn.statically.io , everything just stopped at the inscription "Welcome to Windows", and that's it

**Comment by fatalcoder524** [comment]
This works for me in Win 11. Don't have a Win 7 device to test.
`
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $((irm -useb 'https://cdn.jsdelivr.net/gh/amd64fox/SpotX@master/Install.ps1')) } -new_theme"
`

**Comment by amd64fox** [comment]
@fatalcoder524 
yeah, I completely forgot about `jsdelivr`, it works in win 7
btw, why did you remove `.Content` ? )

**Comment by fatalcoder524** [comment]
It was giving in raw content instead of content. So I moved it to `irm` instead of `iwr`.

**Comment by CoderGuy168** [comment]
It got fixed thanks 
Any Idea why it happens?

**Comment by amd64fox** [comment]
Changed to jsdelivr

**Comment by amd64fox** [comment]
Wow. It seems that jsdelivr is also addressing issues with outdated certificates for Windows 7-8.1

now can get rid of it:
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
or

```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072
```

**Comment by amd64fox** [comment]
I rolled back the method using jsdelivr because it has a rather peculiar system for updating files to the latest version. During testing, it was found that this process can take up to 24 hours or even longer, even when using the `@latest` tag in the link.

**Comment by amd64fox** [comment]
attempting to fix the issue using GitHub pages

**Comment by Xe-ro7** [comment]
Is it fixed? Now we can patch it without VPN right?

**Comment by amd64fox** [comment]
In theory, yes, but it's not definite 😊
Download the updated .bat file or copy the new command to run from PowerShell.

**Comment by Xe-ro7** [comment]
> In theory, yes, but it's not definite 😊
> Download the updated .bat file or copy the new command to run from PowerShell.

Thanks a lot! It's working now!
